### ISSUE TITLE
the test "getDurationTest" in logic.NavigationTest was failed 

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/SmartCity-ParkingManagement#100]
```
java.lang.AssertionError: expected:<82> but was:<84>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at logic.NavigationTest.getDurationTest(NavigationTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

@dshames , I assign this to you since you're probably the one who wrote this test. Be free to assign someone else from the logic team if you're too busy, but all tests need to pass till the end of the sprint.

**Comment by dshames** [comment]
fixed. since the google maps api returns durations based on real time data there might be minor changes. for example, this durations changed from 82 seconds to 84 seconds.

can you think of a better way to do this test so we don't have to change the test every few weeks?
A one I can think of, is check if the expected duration minus the result duration is in some delta of 5 seconds for example. what do you think?

**Comment by zahimizrahi** [comment]
the purpose of the test is to see whether the distance if correct. if you use delta of the distance, you won't test if the distance is precise.
Also, what if the precise distance will go over the delta (probably not, but it can happen)? It won't pass the test, even though it need to pass it.

**Comment by dshames** [comment]
The test failed because the **driving times** sometimes change due to changes of traffic inside the Technion.
I changed the test to check the **walking time** instead which is not effected by traffics.
The test still checks the same: the time to get from point A to point B.
